# Generated by Django 4.2.7 on 2025-12-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, help_text='Event image URL', max_length=500, null=True),
        ),
    ]
